---
  - hosts: docker
    become: true
    
    roles:
      - role: gitlab-runner
        tags: gitlab-runner
      - role: docker
        tags: docker

# - hosts: all
#   tasks:
#     - name: reboot host(s)
#       ansible.builtin.reboot:
#         msg: "reboot by Ansible"
#         pre_reboot_delay: 5
#         post_reboot_delay: 10
#         test_command: "whoami"








  # - hosts: web_server
  #   become: true
  #   tags: web_server
  #   roles:
  #     - web_server

  # - hosts: all
  #   become: true
  #   tags: common
  #   roles:
  #     - common