---
# tasks file for jenkins

- name: add jenkins key from url to this system
  tags: jenkins
  get_url:
    url: "{{ jenkins_url }}"
    dest: "{{ jenkins_url_dest }}"

- name: add jenkins apt repository entry
  tags: jenkins
  apt_repository:
    repo: '{{ jenkins_repo }}'
    state: present

- name: update
  tags: jenkins
  apt:
    update_cache: yes
    state: latest

- name: Install jenkins
  tags: jenkins
  apt:
    name: jenkins
    state: latest

- name: Start jenkins
  tags: always
  service:
    name: jenkins
    enabled: true
    state: started
  notify:
  - restart jenkins

