---
# tasks file for jenkins

- name: add jenkins key from url to this system
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    dest: /usr/share/keyrings/jenkins-keyring.asc

- name: add jenkins apt repository entry
  apt_repository: repo='deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/' state=present
      
- name: update
  apt:
    update_cache: yes
    state: latest

- name: Install java
  apt:
    name: openjdk-11-jdk
    state: present

- name: Install jenkins
  apt:
    name: jenkins
    state: latest

- name: Start jenkins
  service:
    name: jenkins
    enabled: true
    state: started

- name: unarchive apache-maven file
  ansible.builtin.unarchive:
    src: "{{ maven }}"
    dest: "/opt/"
    remote_src: yes
    validate_certs: true
 
- name: Adding JAVA path in the bashrc files
  lineinfile: 
    dest: /root/.bashrc 
    line: 'export PATH=$PATH:/lib/jvm/java-11-openjdk-amd64/bin' 
    insertafter: 'EOF' 
    regexp: 'export PATH=\$PATH:/lib/jvm/java-11-openjdk-amd64/bin'
    state: present

- name: Adding MAVEN path in the bashrc files
  lineinfile:
    dest: /root/.bashrc
    line: 'export PATH=$PATH:/opt/apache-maven-3.1.1/bin'
    insertafter: 'EOF'
    regexp: 'export PATH=\$PATH:/opt/apache-maven-3.1.1/bin'
    state: present
