---

- name: Install java
  apt:
    name: openjdk-11-jdk
    state: present
  tags: java, install, openjdk

- name: Adding JAVA path in the bashrc files
  lineinfile:
#  tags: path, java
    dest: /root/.bashrc
    line: 'export PATH=$PATH:{{ java_path  }}'
    insertafter: 'EOF'
    regexp: 'export PATH=$PATH:{{ java_path  }}'
    state: present
  tags: path, java
