---

- name: Install java
  apt:
    name: openjdk-11-jdk
    state: present

- name: Adding JAVA path in the bashrc files
  lineinfile:
    dest: /root/.bashrc
    line: 'export PATH=$PATH:/lib/jvm/java-11-openjdk-amd64/bin'
    insertafter: 'EOF'
    regexp: 'export PATH=\$PATH:/lib/jvm/java-11-openjdk-amd64/bin'
    state: present

