---
- name: unarchive apache-maven file
  ansible.builtin.unarchive:
    src: "{{ maven }}"
    dest: "/opt/"
    remote_src: yes
    validate_certs: true

- name: Adding MAVEN path in the bashrc files
  lineinfile:
    dest: /root/.bashrc
    line: 'export PATH=$PATH:/opt/apache-maven-3.1.1/bin'
    insertafter: 'EOF'
    regexp: 'export PATH=\$PATH:/opt/apache-maven-3.1.1/bin'
    state: present


