---
- name: unarchive apache-maven file
  ansible.builtin.unarchive:
    src: "{{ maven }}"
    dest: "/opt/"
    remote_src: yes
    validate_certs: true
  tags: maven

- name: Adding MAVEN path in the bashrc files
  lineinfile:
#  tags: path, maven
    dest: /root/.bashrc
    line: 'export PATH=$PATH:{{ maven_path }}'
    insertafter: 'EOF'
    regexp: 'export PATH=$PATH:{{ maven_path }}'
    state: present
  tags: path, maven


