---
# tasks file for nodejs
  - name: Install curl
    apt:
      name: curl
      state: present

#  - name: Install the nodejs
#    apt:
#      name: nodejs
#      state: present


  - name: add nodejs repository 
    shell: |
      curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash - 
    state: present
    update_cache: yes
    
  - name: install nodejs
    apt:
      name: nodejs
      state: present
      
      
