---
# tasks file for nodejs
- name: Install curl
  apt:
    name: curl
    state: present

- name: add nodejs repository 
  state: present
  update_cache: yes
  shell: |
    curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash - 
    
    
- name: install nodejs
  apt:
    name: nodejs
    state: present
      
      
