---
# tasks file for base

- name: create devops user
  user:
    name: ubuntu
    shell: /bin/bash
    groups: root
    state: present

- name: add ssh key for devops user
  authorized_key:
    user: ubuntu
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCxzct3qtFioczR6CshKFrnubshtSVCCFCXKonq89+iKreo7llwX900UzX8HbVjX7sYM5MrfDjxEjqIpgh5+bXejXh4dK+Xv9N5EchrlJwz/6YjMeDXoRChG3lAcSJ5qGUT7LD/7MDTri6aPoruGsfdpha5nAPyC+CtnqCrTHZSUC/4K4OL08JsXwgqPSgu/eg8ykptBvQ40uFmtjrhkDgOJe/ZVKAdXBHxFzG/fiUBE1V32fwVnPrnIjVoQBUf0oFG9hcACcpBLfPnbuoO9HeK0uOBQmn2PWJlQtXmQu3dWKE/YkEmklZy6ARykqqwsexswDnO4A7g93zxrrAjGpGiUxVTaEkTQ0Hz/3qaLLUwCEWjWTyShTA7oh3zI6XUxonBKO9NzymJpPXvsDPS/HiS9W4GuFYs51YQX4UbADQho00fuK0hy0b6TXktXcPewXj4iY+zkN32vwHu0gI7WuIy9XZR9dGsT2yleGlNW6M7CBQLhXgvNz32HDk6edoUc1s= ansible key"

- name: add sudoers file for devops user
  tags: always
  copy:
    src: sudoer_ubuntu
    dest: /etc/sudoers.d/ubuntu
    owner: root
    group: root
    mode: 0644
